apiVersion: v1
kind: Secret
metadata:
  name: jobquest-secret
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb+srv://jobquest:23020510@mal.wjbixqu.mongodb.net/?appName=mal"
  AUTH0_DOMAIN: "dev-eguwptuph5frre71.us.auth0.com"
  AUTH0_CLIENT_ID: "KnQ4tvaIGPrnGuhOpkCd4Amn0XVeD7pT"
  JWT_SECRET: "THIS_is_a_SUPER_LONG_secret_key_at_least_32_bytes_123456"
